### ISSUE TITLE
Rth_heatsink Parameter Sweep

### ISSUE THREAD

**Issue by caneryagci** [caneryagci/Star#3]
Merhaba Hocam,
Simulink modelimdeki  "Rth_heatsink" bloğunun değerini m.file üzerinden sweep ederek farklı Rth_heatsink (x-axis)değerleri için Tj IGBT, Tj FWD, etc. (y-axis) grafiği oluşturmaya çalışıyorum.

Bunun için "set_param" fonksiyonunu kullanarak simulink modelimi for loop içinde döndürmeye çalıştım ama errorlerden kurtulamadım. 

1-Simulink parametremin değerini tek bir run içinde değiştirebilir miyim ? ya da 
2-Yapmak istediğim grafiği nasıl oluşturabilirim? 
3-Logging'i nasıl kullanabilirim?

Şuan için Rth (heatsink) değerini tek tek elimle girip sırayla run ederek değerlerden excel dosyası oluşturup plot etmeyi düşünüyorum ama eminim ki daha verimli bir yol vardır :D

@ozank @mesutto

**Comment by mesutto** [comment]
Selam Caner,

Ben bu issue'yu atlamışım kusura bakma şimdi gördüm.

Ekstra fonksiyon kullanmana gerek yok. .m file içinde Rth_hs = x şeklinde assign edip, simulasyon modelinde de direnç değerine Rth_hs yazarsan simulink onu tanıyacaktır. Sonra .m file'da "sim" fonksiyonu ile simulasyonu çağırabilirsin, ve simulasyon sonuçlarını workspace'e attıktan sonra o iterasyondaki değeri bir array'e kaydedebilirsin. Böyle tüm iterasyonlar bittiğinde her iterasyondaki Tj değerlerinin kaydedildiği bir array'in olmuş olacak. 

Evet, her zaman elle yapmaktan daha verimli bir yol var. :) Bugün toplantıda detaylı bakarız.

Eline sağlık !
